In [1]:
import cv2
import matplotlib.pyplot as plt
import numpy as np
import time
from scipy.spatial.transform import Rotation

# from estimate_pose_dlt import estimatePoseDLT
# from reproject_points import reprojectPoints
# from draw_camera import drawCamera

In [2]:
all_pts_2d = np.loadtxt("/home/mullin/WorkSpace/CourseProject/3 VAMR/Exercise 2 - PnP/data/detected_corners.txt")

In [3]:
row, column = all_pts_2d.shape

In [4]:
all_pts_2d

array([[186.5, 187.5, 264.5, ..., 280.5, 496.5, 300.5],
       [186.5, 186.5, 264.5, ..., 279.5, 496.5, 300.5],
       [187.5, 186.5, 265.5, ..., 279.5, 496.5, 300.5],
       ...,
       [220.5, 216.5, 293.5, ..., 306.5, 547.5, 319.5],
       [214.5, 226.5, 289.5, ..., 313.5, 542.5, 327.5],
       [208.5, 236.5, 283.5, ..., 322.5, 537.5, 336.5]])

In [5]:
p_1 = all_pts_2d[1,:]

In [6]:
p_1

array([186.5, 186.5, 264.5, 166.5, 217.5, 303.5, 285.5, 269.5, 291.5,
       369.5, 355.5, 322.5, 405.5, 418.5, 462.5, 352.5, 388.5, 204.5,
       495.5, 211.5, 396.5, 279.5, 496.5, 300.5])

In [7]:
p_1[1]

186.5

In [8]:
pixel = np.ones((3, int(column/2)))

In [9]:
pixel_mat = np.mat(pixel)

In [10]:
pixel

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [11]:
pixel[0][0]

1.0

In [12]:
pixel_mat

matrix([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [13]:
pixel_mat[1,1]

1.0

In [14]:
for i in range(int(column/2)):
    pixel[0][i] = p_1[2*i]
    pixel[1][i] = p_1[2*i+1]
    pixel[2][i] = 1

In [15]:
pixel

array([[186.5, 264.5, 217.5, 285.5, 291.5, 355.5, 405.5, 462.5, 388.5,
        495.5, 396.5, 496.5],
       [186.5, 166.5, 303.5, 269.5, 369.5, 322.5, 418.5, 352.5, 204.5,
        211.5, 279.5, 300.5],
       [  1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,   1. ,
          1. ,   1. ,   1. ]])

In [16]:
for i in range(int(column/2)):
    pixel_mat[0,i] = p_1[2*i]
    pixel_mat[1,i] = p_1[2*i+1]
    pixel_mat[2,i] = 1

In [ ]:
pixel_mat

In [ ]:
np.mat(pixel)

In [ ]:
pixel_mat == np.mat(pixel)

In [20]:
K = np.loadtxt("/home/mullin/WorkSpace/CourseProject/3 VAMR/Exercise 2 - PnP//data/K.txt")

In [21]:
K

array([[420.506712,   0.      , 355.208298],
       [  0.      , 420.61094 , 250.336787],
       [  0.      ,   0.      ,   1.      ]])

In [22]:
K = np.mat(K)

In [23]:
k_inv = K.I

In [24]:
k_inv

matrix([[ 0.00237808,  0.        , -0.84471493],
        [ 0.        ,  0.00237749, -0.59517422],
        [ 0.        ,  0.        ,  1.        ]])

In [25]:
pixel_mat[0,:]

matrix([[186.5, 264.5, 217.5, 285.5, 291.5, 355.5, 405.5, 462.5, 388.5,
         495.5, 396.5, 496.5]])

In [26]:
pixel_mat[:,0]

matrix([[186.5],
        [186.5],
        [  1. ]])

In [33]:
k_inv*pixel_mat[:,0]

matrix([[-0.40120239],
        [-0.15177158],
        [ 1.        ]])

In [28]:
k_inv*np.mat([100,100,1]).T

matrix([[-0.6069066 ],
        [-0.35742481],
        [ 1.        ]])

In [29]:
p_c = np.mat(np.zeros((3,int(column/2))))

In [31]:
for i in range (int(column/2)):
    p_c[:,i]=k_inv*pixel_mat[:,i]

In [32]:
p_c

matrix([[-4.01202390e-01, -2.15711891e-01, -3.27481807e-01,
         -1.65772141e-01, -1.51503641e-01,  6.93691662e-04,
          1.19597858e-01,  2.55148607e-01,  7.91704414e-02,
          3.33625357e-01,  9.81951080e-02,  3.36003441e-01],
        [-1.51771580e-01, -1.99321461e-01,  1.26395222e-01,
          4.55604246e-02,  2.83309828e-01,  1.71567608e-01,
          3.99807035e-01,  2.42892429e-01, -1.08976688e-01,
         -9.23342293e-02,  6.93353649e-02,  1.19262740e-01],
        [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
          1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
          1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
          1.00000000e+00,  1.00000000e+00,  1.00000000e+00]])

In [41]:
p_c_d = p_c[0:2,:]

In [42]:
p_c_d

matrix([[-0.40120239, -0.21571189, -0.32748181, -0.16577214, -0.15150364,
          0.00069369,  0.11959786,  0.25514861,  0.07917044,  0.33362536,
          0.09819511,  0.33600344],
        [-0.15177158, -0.19932146,  0.12639522,  0.04556042,  0.28330983,
          0.17156761,  0.39980704,  0.24289243, -0.10897669, -0.09233423,
          0.06933536,  0.11926274]])

In [122]:
p_c_d[:,0]

matrix([[-0.40120239],
        [-0.15177158]])

In [43]:
p_W_corners = np.loadtxt("/home/mullin/WorkSpace/CourseProject/3 VAMR/Exercise 2 - PnP//data/p_W_corners.txt", delimiter = ",")

In [44]:
p_W_corners

array([[  0.  ,   8.  ,   0.  ],
       [ 10.4 ,   8.  ,   0.  ],
       [  0.  ,  21.5 ,   0.  ],
       [ 10.4 ,  21.5 ,   0.  ],
       [  0.  ,  26.6 , -10.95],
       [ 10.4 ,  26.6 , -10.95],
       [  0.  ,  26.6 , -24.45],
       [ 10.4 ,  26.6 , -24.45],
       [ 19.4 ,  14.6 , -10.95],
       [ 19.4 ,  14.6 , -24.45],
       [ 19.4 ,  25.  , -10.95],
       [ 19.4 ,  25.  , -24.45]])

In [46]:
p_W_mat = np.mat(p_W_corners)

In [58]:
p_W_mat_h = np.hstack((p_W_mat,np.mat(np.ones((12,1)))))

In [59]:
p_W_mat_h

matrix([[  0.  ,   8.  ,   0.  ,   1.  ],
        [ 10.4 ,   8.  ,   0.  ,   1.  ],
        [  0.  ,  21.5 ,   0.  ,   1.  ],
        [ 10.4 ,  21.5 ,   0.  ,   1.  ],
        [  0.  ,  26.6 , -10.95,   1.  ],
        [ 10.4 ,  26.6 , -10.95,   1.  ],
        [  0.  ,  26.6 , -24.45,   1.  ],
        [ 10.4 ,  26.6 , -24.45,   1.  ],
        [ 19.4 ,  14.6 , -10.95,   1.  ],
        [ 19.4 ,  14.6 , -24.45,   1.  ],
        [ 19.4 ,  25.  , -10.95,   1.  ],
        [ 19.4 ,  25.  , -24.45,   1.  ]])

In [73]:
p_W_mat_h[0:2,:]

matrix([[ 0. ,  8. ,  0. ,  1. ],
        [10.4,  8. ,  0. ,  1. ]])

In [140]:
Q = np.mat(np.zeros((column,12)))

In [118]:
Q[1,:]

matrix([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [150]:
-p_W_mat_h[1]

matrix([[-10.4,  -8. ,  -0. ,  -1. ]])

In [148]:
p_c_d[0,1]

-0.21571189094360999

In [153]:
-p_W_mat_h[1]*p_c_d[1,1]

matrix([[2.07294319, 1.59457169, 0.        , 0.19932146]])

In [154]:
for i in range (int(column/2)):
    Q[2*i, 0:4] = p_W_mat_h[i]
    Q[2*i, 8:12] = p_W_mat_h[i] * (-1) * p_c_d[0,i]
    Q[2*i+1, 4:8] = p_W_mat_h[i]
    Q[2*i+1, 8:12] = p_W_mat_h[i] * (-1) * p_c_d[1,i]

In [155]:
print((Q))

[[ 0.00000000e+00  8.00000000e+00  0.00000000e+00  1.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  3.20961912e+00  0.00000000e+00  4.01202390e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  8.00000000e+00  0.00000000e+00  1.00000000e+00
   0.00000000e+00  1.21417264e+00  0.00000000e+00  1.51771580e-01]
 [ 1.04000000e+01  8.00000000e+00  0.00000000e+00  1.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   2.24340367e+00  1.72569513e+00  0.00000000e+00  2.15711891e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   1.04000000e+01  8.00000000e+00  0.00000000e+00  1.00000000e+00
   2.07294319e+00  1.59457169e+00  0.00000000e+00  1.99321461e-01]
 [ 0.00000000e+00  2.15000000e+01  0.00000000e+00  1.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  7.04085886e+00  0.00000000e+00  3.27481807e-01]
 [ 0.