## 导入与函数

In [1]:
import numpy as np

In [2]:
def cross2Matrix(x):
    """ Antisymmetric matrix corresponding to a 3-vector
     Computes the antisymmetric matrix M corresponding to a 3-vector x such
     that M*y = cross(x,y) for all 3-vectors y.

     Input: 
       - x np.ndarray(3,1) : vector

     Output: 
       - M np.ndarray(3,3) : antisymmetric matrix
    """
    M = np.array([[0,   -x[2], x[1]], 
                  [x[2],  0,  -x[0]],
                  [-x[1], x[0],  0]])
    return M

## Test for single point

In [3]:
P = np.random.rand(4,1)

# Test linear triangulation
P[2, :] = P[2, :] * 5 + 10
P[3, :] = 1


M1 = np.array([ [500,   0,      320,    0],
                [0,     500,    240,    0],
                [0,     0,      1,      0]])

M2 = np.array([ [500,   0,      320,    -100],
                [0,     500,    240,    0],
                [0,     0,      1,      0]])

p1 = M1 @ P
p2 = M2 @ P

In [4]:
print(P)
print(p1)
print(p2)

[[ 0.11399017]
 [ 0.2511884 ]
 [14.07252407]
 [ 1.        ]]
[[4560.20278931]
 [3502.99997934]
 [  14.07252407]]
[[4460.20278931]
 [3502.99997934]
 [  14.07252407]]


In [5]:
p1.squeeze()

array([4560.20278931, 3502.99997934,   14.07252407])

In [6]:
p1_x = cross2Matrix(p1.squeeze())
p2_x = cross2Matrix(p2.squeeze())

In [7]:
print(p1_x)
print(p2_x)

[[    0.           -14.07252407  3502.99997934]
 [   14.07252407     0.         -4560.20278931]
 [-3502.99997934  4560.20278931     0.        ]]
[[    0.           -14.07252407  3502.99997934]
 [   14.07252407     0.         -4460.20278931]
 [-3502.99997934  4460.20278931     0.        ]]


In [12]:
p1_x@M1

array([[ 0.00000000e+00, -5.30194208e+03,  4.68418310e+02,
         0.00000000e+00],
       [ 5.30194208e+03,  0.00000000e+00, -2.29313499e+02,
         0.00000000e+00],
       [-1.50667525e+06,  1.81127822e+06, -9.48586196e+04,
         0.00000000e+00]])

In [15]:
p2_x@M2

array([[ 0.00000000e+00, -5.30194208e+03,  4.68418310e+02,
         0.00000000e+00],
       [ 5.30194208e+03,  0.00000000e+00, -1.29313499e+02,
        -1.06038842e+03],
       [-1.50667525e+06,  1.76127822e+06, -1.18858620e+05,
         3.01335051e+05]])

In [18]:
A = np.r_[p1_x@M1, p2_x@M2]

In [19]:
A.shape

(6, 4)

In [20]:
U,sigma, VT = np.linalg.svd(A,full_matrices=True)

In [22]:
VT.T[:,-1]

array([-0.04285478, -0.0875394 , -0.99084258, -0.09344148])

In [23]:
VT.T[3,-1]

-0.09344147500687267

In [25]:
P_est = VT.T[:,-1] / VT.T[3,-1]

In [26]:
P_est

array([ 0.458627  ,  0.93683662, 10.60388416,  1.        ])

## Def LinearTriangulation_Single 

In [31]:
def linearTriangulation_single(p1, p2, M1, M2):
    """ Linear Triangulation
     Input:
      - p1 np.ndarray(3, 1): homogeneous coordinates of points in image 1
      - p2 np.ndarray(3, 1): homogeneous coordinates of points in image 2
      - M1 np.ndarray(3, 4): projection matrix corresponding to first image
      - M2 np.ndarray(3, 4): projection matrix corresponding to second image

     Output:
      - P np.ndarray(4, N): homogeneous coordinates of 3-D points
    """
    
    p1_x = cross2Matrix(p1.squeeze())
    p2_x = cross2Matrix(p2.squeeze())
    A = np.r_[p1_x@M1, p2_x@M2]
    U,sigma, VT = np.linalg.svd(A,full_matrices=True)
    P_est = VT.T[:,-1] / VT.T[3,-1]
    return P_est


## Test  

In [112]:
# Number of 3D points to test
N = 10

# Random homogeneous coordinates of 3-D points
P = np.random.rand(4,N)

# Test linear triangulation
P[2, :] = P[2, :] * 5 + 10
P[3, :] = 1


M1 = np.array([ [500,   0,      320,    0],
                [0,     500,    240,    0],
                [0,     0,      1,      0]])

M2 = np.array([ [500,   0,      320,    -100],
                [0,     500,    240,    0],
                [0,     0,      1,      0]])

p1 = M1 @ P
p2 = M2 @ P

In [113]:
P

array([[ 0.55300967,  0.46850847,  0.67099192,  0.07800552,  0.32397558,
         0.52820844,  0.80884159,  0.13667473,  0.87319548,  0.94004699],
       [ 0.34338809,  0.91580039,  0.33199173,  0.43532305,  0.65941655,
         0.23625551,  0.44359341,  0.86329727,  0.17809186,  0.02837914],
       [13.19350861, 13.29977474, 10.23636643, 12.73250876, 10.67004579,
        10.18257285, 12.23047958, 11.03640398, 14.68522163, 12.56625493],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ]])

In [114]:
p1

array([[4498.42758695, 4490.18215215, 3611.13321761, 4113.4055619 ,
        3576.40244578, 3522.52753181, 4318.17426363, 3599.98663674,
        5135.86865945, 4491.22507263],
       [3338.13610869, 3649.84613506, 2622.72380938, 3273.46362636,
        2890.51926655, 2561.94523764, 3157.11180289, 3080.38558885,
        3613.49912026, 3030.09075177],
       [  13.19350861,   13.29977474,   10.23636643,   12.73250876,
          10.67004579,   10.18257285,   12.23047958,   11.03640398,
          14.68522163,   12.56625493]])

In [115]:
p1[:,0]

array([4498.42758695, 3338.13610869,   13.19350861])

In [116]:
p1.shape[1]

10

In [117]:
n_P = p1.shape[1]

In [118]:
A = np.array

In [130]:
for i in range(n_P):
    temp_p1_x = cross2Matrix(p1[:,i].squeeze())
    temp_p2_x = cross2Matrix(p2[:,i].squeeze())
    temp_A_col = np.r_[temp_p1_x@M1, temp_p2_x@M2]
    if i == 0 :
        A = temp_A_col
    else :
        A = np.r_[A, temp_A_col]

In [132]:
A.shape

(60, 4)

In [121]:
U,sigma, VT = np.linalg.svd(A,full_matrices=True)

In [122]:
VT.T[:,-1]

array([-4.54609198e-02, -1.72641054e-01, -1.40728751e-01, -8.84301529e-02,
        2.60813369e-01,  3.97433502e-01, -1.21999436e-04,  6.44508590e-02,
       -2.64715761e-02, -6.14329716e-02,  1.44595256e-02, -1.10162582e-01,
       -3.58934226e-02, -6.60623334e-02,  1.32055088e-02, -1.27438426e-01,
       -6.91419986e-02, -9.45884909e-02,  6.14080929e-03,  1.94400645e-02,
       -1.38699491e-02, -8.19595579e-02,  1.71460004e-02, -1.49857641e-01,
       -3.78506146e-02, -9.40509113e-03,  1.17074967e-02, -1.11515286e-01,
       -9.55468858e-02, -1.08562713e-01,  2.00325677e-03,  9.77659658e-02,
        1.56079964e-03,  7.18962392e-02,  1.86751132e-02, -2.85809618e-01,
        1.77790211e-02,  4.33089012e-02,  2.23050731e-02,  7.02291803e-01])

In [123]:
P_unsc = VT.T[:,-1].reshape(10,4)

In [124]:
P_unsc

array([[-4.54609198e-02, -1.72641054e-01, -1.40728751e-01,
        -8.84301529e-02],
       [ 2.60813369e-01,  3.97433502e-01, -1.21999436e-04,
         6.44508590e-02],
       [-2.64715761e-02, -6.14329716e-02,  1.44595256e-02,
        -1.10162582e-01],
       [-3.58934226e-02, -6.60623334e-02,  1.32055088e-02,
        -1.27438426e-01],
       [-6.91419986e-02, -9.45884909e-02,  6.14080929e-03,
         1.94400645e-02],
       [-1.38699491e-02, -8.19595579e-02,  1.71460004e-02,
        -1.49857641e-01],
       [-3.78506146e-02, -9.40509113e-03,  1.17074967e-02,
        -1.11515286e-01],
       [-9.55468858e-02, -1.08562713e-01,  2.00325677e-03,
         9.77659658e-02],
       [ 1.56079964e-03,  7.18962392e-02,  1.86751132e-02,
        -2.85809618e-01],
       [ 1.77790211e-02,  4.33089012e-02,  2.23050731e-02,
         7.02291803e-01]])

In [125]:
P_unsc[1,]

array([ 2.60813369e-01,  3.97433502e-01, -1.21999436e-04,  6.44508590e-02])

In [126]:
P_unsc[i,3] 

0.7022918031018758

In [127]:
P_est = np.ones_like(P_unsc)
for i in range (P_unsc.shape[0]):
    P_est[i,] = P_unsc[i,] / P_unsc[i,3] 

In [137]:
P_est.shape

(10, 4)

In [142]:
p1[:,1]

array([4490.18215215, 3649.84613506,   13.29977474])

In [145]:
    p_size = p1.shape[1]
    P_est = np.ones([p_size,4])
    for i in range (p_size):
        temp_p1_x = cross2Matrix(p1[:,i].squeeze())
        temp_p2_x = cross2Matrix(p2[:,i].squeeze())
        temp_A = np.r_[temp_p1_x@M1, temp_p2_x@M2]
        _,_, VT = np.linalg.svd(temp_A,full_matrices=True)
        P_est[i,]  = VT.T[:,-1] / VT.T[3,-1]   

In [136]:
temp_P_est

array([-3.58224982e+03, -2.68663762e+03,  5.61335650e+03,  1.00000000e+00])

In [147]:
P_est.T

array([[ 0.55300967,  0.46850847,  0.67099192,  0.07800552,  0.32397558,
         0.52820844,  0.80884159,  0.13667473,  0.87319548,  0.94004699],
       [ 0.34338809,  0.91580039,  0.33199173,  0.43532305,  0.65941655,
         0.23625551,  0.44359341,  0.86329727,  0.17809186,  0.02837914],
       [13.19350861, 13.29977474, 10.23636643, 12.73250876, 10.67004579,
        10.18257285, 12.23047958, 11.03640398, 14.68522163, 12.56625493],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ]])

In [129]:
P

array([[ 0.55300967,  0.46850847,  0.67099192,  0.07800552,  0.32397558,
         0.52820844,  0.80884159,  0.13667473,  0.87319548,  0.94004699],
       [ 0.34338809,  0.91580039,  0.33199173,  0.43532305,  0.65941655,
         0.23625551,  0.44359341,  0.86329727,  0.17809186,  0.02837914],
       [13.19350861, 13.29977474, 10.23636643, 12.73250876, 10.67004579,
        10.18257285, 12.23047958, 11.03640398, 14.68522163, 12.56625493],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         1.        ,  1.        ,  1.        ,  1.        ,  1.        ]])

## Def LinearTriangulation

In [8]:
def linearTriangulation(p1, p2, M1, M2):
    """ Linear Triangulation
     Input:
      - p1 np.ndarray(3, N): homogeneous coordinates of points in image 1
      - p2 np.ndarray(3, N): homogeneous coordinates of points in image 2
      - M1 np.ndarray(3, 4): projection matrix corresponding to first image
      - M2 np.ndarray(3, 4): projection matrix corresponding to second image

     Output:
      - P np.ndarray(4, N): homogeneous coordinates of 3-D points
    """
    p_size = p1.shape[1]
    P_est = np.ones([p_size,4])
    for i in range (p_size):
        temp_p1_x = cross2Matrix(p1[:,i].squeeze())
        temp_p2_x = cross2Matrix(p2[:,i].squeeze())
        temp_A = np.r_[temp_p1_x@M1, temp_p2_x@M2]
        _,_, VT = np.linalg.svd(temp_A,full_matrices=True)
        P_est[i,]  = VT.T[:,-1] / VT.T[3,-1]   

    
    return P_est.T


##  Run_Test_LinearTriangulation

In [9]:
# Number of 3D points to test
N = 10

# Random homogeneous coordinates of 3-D points
P = np.random.rand(4,N)

# Test linear triangulation
P[2, :] = P[2, :] * 5 + 10
P[3, :] = 1


M1 = np.array([ [500,   0,      320,    0],
                [0,     500,    240,    0],
                [0,     0,      1,      0]])

M2 = np.array([ [500,   0,      320,    -100],
                [0,     500,    240,    0],
                [0,     0,      1,      0]])

p1 = M1 @ P
p2 = M2 @ P

P_est = linearTriangulation(p1, p2, M1, M2)

print('P_est - P')
print(P_est - P)
print("Your function looks %s" % ("Correct" if np.allclose(P_est, P) else "Incorrect"))


P_est - P
[[-3.33066907e-15  1.05471187e-15  2.77555756e-15 -3.83026943e-14
  -2.32036612e-14 -1.99285033e-14 -4.60742555e-15 -3.28626015e-14
  -2.55351296e-15 -1.99840144e-15]
 [-6.66133815e-16 -6.66133815e-16  2.16493490e-15 -2.89768209e-14
  -1.62508895e-14 -1.65978342e-14 -3.71924713e-15 -2.23154828e-14
  -1.66533454e-15 -1.27675648e-15]
 [-7.10542736e-15 -2.30926389e-14 -7.10542736e-15  1.42108547e-14
   1.77635684e-14  1.95399252e-14  1.77635684e-14  5.50670620e-14
   0.00000000e+00  8.88178420e-15]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]]
Your function looks Correct
